# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: roomie
      password: Vbn2309
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: roomie_development

test:
  <<: *default
  database: roomie_test

production:
  <<: *default
  database: app_production
